export const HUMAN_PROVIDERS: Record<string, { label: string; logo: string; image?: string; color: string }> = {
    gemini: { label: "Google Gemini", logo: "♊", image: "/gemini.png", color: "#8E75C8" },
    groq: { label: "Groq Speed API", logo: "⚡", image: "/groq llama.svg", color: "#F59E0B" },
    claude: { label: "Anthropic Claude", logo: "🍁", image: "/claude.png", color: "#D97706" },
    sambanova: { label: "SambaNova Systems", logo: "🌐", image: "/sambanova.png", color: "#2563EB" },
    deepseek: { label: "DeepSeek API", logo: "🐋", image: "/deepseek.png", color: "#0D9488" },
    cerebras: { label: "Cerebras Systems", logo: "🎛️", image: "/cerebras.png", color: "#EF4444" },
    ollama: { label: "Ollama (Local)", logo: "🐑", image: "/groq llama.svg", color: "#10B981" },
};

export const HUMAN_MODELS = [
    { value: "gemini-2.5-flash-lite", label: "Gemini 2.5 Flash Lite (Rápido & Econômico)", description: "Otimizado para latência ultra-baixa em tarefas simples." },
    { value: "gemini-2.5-flash", label: "Gemini 2.5 Flash (Padrão)", description: "Equilíbrio ideal entre velocidade e raciocínio contextual." },
    { value: "gemini-2.5-pro", label: "Gemini 2.5 Pro (Alta Fidelidade)", description: "Raciocínio complexo e janela de contexto de 1M+ tokens." },
    { value: "gemini-flash-latest", label: "Gemini Flash Latest", description: "Última versão de produção do modelo de alta velocidade do Google Gemini." },
    { value: "gemini-2.0-flash-exp", label: "Gemini 2.0 Flash Exp (Experimental)", description: "Versão experimental de próxima geração para testes do Gemini Flash." },
    { value: "gemini-1.5-flash", label: "Gemini 1.5 Flash (Multimodal)", description: "Modelo multimídia eficiente e altamente estável do Google." },
    { value: "llama-3.3-70b-versatile", label: "Llama 3.3 70B Versatile (Meta / Groq)", description: "Poder analítico de 70B com a velocidade absurda do hardware LPU." },
    { value: "llama-3.1-8b-instant", label: "Llama 3.1 8B Instant (Rápido / Groq)", description: "Espinha dorsal para interações de alta frequência e baixa latência." },
    { value: "meta-llama/llama-4-scout-17b-16e-instruct", label: "Llama 4 Scout 17B (Groq / SambaNova)", description: "Nova geração Llama 4 otimizada para eficiência e precisão." },
    { value: "qwen/qwen3-32b", label: "Qwen 3 32B (Groq / Alibaba)", description: "Excelente performance em lógica, matemática e codificação." },
    { value: "llama-3.2-11b-vision-preview", label: "Llama 3.2 11B Vision (Groq)", description: "Análise visual, OCR e interpretação de imagens em tempo real." },
    { value: "groq/compound", label: "Groq Compound System", description: "Sistema autônomo com busca web e execução de código nativa." },
    { value: "mixtral-8x7b-32768", label: "Mixtral 8x7B MoE (Groq)", description: "Arquitetura Mixture-of-Experts para respostas versáteis." },
    { value: "claude-3-5-sonnet-latest", label: "Claude 3.5 Sonnet (Anthropic)", description: "O 'cérebro' para análise estratégica e escrita refinada." },
    { value: "claude-3-5-haiku-latest", label: "Claude 3.5 Haiku (Anthropic)", description: "Rápido e preciso para extração de dados estruturados." },
    { value: "Llama-4-Scout-17B-16E-Instruct", label: "Llama 4 Scout 17B (SambaNova)", description: "Performance Llama 4 em infraestrutura RDU de alta densidade." },
    { value: "Meta-Llama-3.3-70B-Instruct", label: "Llama 3.3 70B (SambaNova)", description: "Modelo 70B completo rodando em hardware SambaNova." },
    { value: "deepseek-chat", label: "DeepSeek Chat V3", description: "Modelo versátil com excelente custo-benefício e lógica." },
    { value: "llama3.1-8b", label: "Llama 3.1 8B (Cerebras)", description: "Velocidade supersônica via hardware CS-3." },
    { value: "llama-3.3-70b", label: "Llama 3.3 70B (Cerebras)", description: "70B com latência mínima recorde na indústria." },
    { value: "qwen-3-235b-a22b-instruct-2507", label: "Qwen 3 235B Instruct (Alibaba / Cerebras)", description: "Modelo gigante executado em velocidade inacreditável via hardware Cerebras CS-3." },
    { value: "qwen-3-235b-instruct", label: "Qwen 3 235B Instruct (Cerebras)", description: "Modelo de 235 bilhões de parâmetros com extrema profundidade cognitiva." },
    { value: "gpt-oss-120b", label: "GPT OSS 120B (Cerebras)", description: "Modelo open-source de grande porte para orquestração avançada." },
    { value: "zai-glm-4.7", label: "GLM 4.7 (Cerebras)", description: "Modelo de raciocínio lógico claro com suporte nativo a thinking." },
    { value: "qwen2.5:3b", label: "Qwen 2.5 3B (Ollama Local)", description: "Privacidade total rodando localmente na sua máquina (3B)." },
    { value: "qwen2.5:1.5b", label: "Qwen 2.5 1.5B (Ollama Local)", description: "Modelo leve rodando em hardware local para máxima eficiência e privacidade (1.5B)." },
];
