"""Add prospecting context

Revision ID: fe848caeb89c
Revises: 8c17a923638a
Create Date: 2026-05-25 15:52:17.894217

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fe848caeb89c'
down_revision: Union[str, None] = '8c17a923638a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employees', sa.Column('prospecting_context', sa.Text(), nullable=True))
    op.create_index(op.f('ix_employees_temperature'), 'employees', ['temperature'], unique=False)
    
    op.add_column('organizations', sa.Column('temperature', sa.String(), nullable=True))
    op.add_column('organizations', sa.Column('prospecting_context', sa.Text(), nullable=True))
    op.create_index(op.f('ix_organizations_temperature'), 'organizations', ['temperature'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_organizations_temperature'), table_name='organizations')
    op.drop_index(op.f('ix_organizations_source'), table_name='organizations')
    op.drop_index(op.f('ix_organizations_product_focus'), table_name='organizations')
    op.drop_index(op.f('ix_organizations_last_enrichment'), table_name='organizations')
    op.drop_index(op.f('ix_organizations_is_excluded'), table_name='organizations')
    op.drop_index(op.f('ix_organizations_cnpj'), table_name='organizations')
    op.drop_index(op.f('ix_organizations_category'), table_name='organizations')
    op.drop_index('ix_org_category_focus', table_name='organizations')
    op.drop_index('ix_org_active_recent', table_name='organizations')
    op.create_index(op.f('ix_organizations_icp_tier'), 'organizations', ['icp_tier'], unique=False)
    op.create_index(op.f('ix_organizations_icp_score'), 'organizations', ['icp_score'], unique=False)
    op.alter_column('organizations', 'source',
               existing_type=sa.VARCHAR(),
               server_default=sa.text("'pipedrive'"),
               existing_nullable=True)
    op.drop_column('organizations', 'prospecting_context')
    op.drop_column('organizations', 'temperature')
    op.drop_constraint(None, 'employees', type_='foreignkey')
    op.create_foreign_key(None, 'employees', 'organizations', ['company_id'], ['id'])
    op.drop_index(op.f('ix_employees_whatsapp_number'), table_name='employees')
    op.drop_index(op.f('ix_employees_temperature'), table_name='employees')
    op.drop_index(op.f('ix_employees_source'), table_name='employees')
    op.drop_index(op.f('ix_employees_seniority'), table_name='employees')
    op.drop_index(op.f('ix_employees_pipedrive_id'), table_name='employees')
    op.drop_index(op.f('ix_employees_phone'), table_name='employees')
    op.drop_index(op.f('ix_employees_manager_id'), table_name='employees')
    op.drop_index(op.f('ix_employees_last_scanned'), table_name='employees')
    op.drop_index(op.f('ix_employees_is_discovery'), table_name='employees')
    op.drop_index(op.f('ix_employees_email'), table_name='employees')
    op.drop_index(op.f('ix_employees_company_id'), table_name='employees')
    op.drop_index('ix_emp_company_seniority', table_name='employees')
    op.drop_index('ix_emp_company_manager', table_name='employees')
    op.drop_index('ix_emp_company_department', table_name='employees')
    op.alter_column('employees', 'source',
               existing_type=sa.VARCHAR(),
               server_default=sa.text("'pipedrive'"),
               existing_nullable=True)
    op.alter_column('employees', 'is_discovery',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=True)
    op.alter_column('employees', 'headline',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.drop_column('employees', 'prospecting_context')
    op.drop_index('ix_ccc_org_channel', table_name='contact_conversation_cache')
    op.alter_column('contact_conversation_cache', 'is_key_contact',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.alter_column('contact_conversation_cache', 'has_unread',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=False)
    # ### end Alembic commands ###
